# -*- coding: utf-8 -*-
"""2_pytorch_classification__00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7flhWpQvgJYuCzHy4h4jNYiqd4XmeRz

#Neural network classification with python
"""

#Make some data

import sklearn
from sklearn.datasets import make_circles

n_samples=1000

x,y=make_circles(n_samples,
                 noise=0.03,
                 random_state=42)

len(x),len(y)

print(f"First five X:{x[:5]}")
print(f"First five y:{y[:5]}")

import pandas as pd
circles=pd.DataFrame({"X1":x[:,0],
                      "X2":x[:,1],
                      "label":y})
circles.head(10)

import matplotlib.pyplot as plt
plt.scatter(x=x[:,0],
            y=x[:,1],
            c=y,
            cmap=plt.cm.RdYlBu)

"""#Check input and output shape

"""

x.shape,y.shape

x

x_sample=x[0]
y_sample=y[0]

print(f"One sample of x:{x_sample}and one sample of y:{y_sample}")
print(f"Shape of one sample of x:{x_sample.shape}and shape of one sample of y:{y_sample.shape}")

"""#Turning data into tensor"""

import torch
x=torch.from_numpy(x).type(torch.float)
y=torch.from_numpy(y).type(torch.float)

type(x),x.dtype,y.dtype

#split data into train test
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=42)

len(x_train) , len(x_test) , len(y_train) , len(y_test)

"""#Building a model"""

import torch
from torch import nn

device="cuda" if torch.cuda.is_available() else"cpu"
device

x_train

#Construct a model
class circlemodelv0(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_1=nn.Linear(in_features=2,out_features=5)
    self.layer_2=nn.Linear(in_features=5,out_features=1)

  def forward(self,x):
    return self.layer_2(self.layer_1(x))

model_0=circlemodelv0().to(device)
model_0

device

next(model_0.parameters()).device

# torch.manual_seed(42)
model_0=nn.Sequential(
    nn.Linear(in_features=2,out_features=5),
    nn.Linear(in_features=5,out_features=1)
).to(device)

model_0

model_0.state_dict()

untrained_preds=model_0(x_test.to(device))
print(f"Length of Prediction:{len(untrained_preds)} and shape:{untrained_preds.shape}")
print(f"Length of Test samples:{len(x_test)} and shape:{x_test.shape}")

"""#Set up loss function"""

loss_fn=nn.BCEWithLogitsLoss()
optimizer=torch.optim.SGD(params=model_0.parameters(),
                          lr=0.1)

model_0.state_dict()

def accuracy_fn(y_true,y_pred):
  correct=torch.eq(y_true,y_pred).sum().item()
  acc=(correct/len(y_pred))*100
  return acc

"""#Train model"""

model_0.eval()
with torch.inference_mode():
  y_logits=model_0(x_test.to(device)[:5])
y_logits

y_pred_prob=torch.sigmoid(y_logits)
y_pred_prob

y_pred=torch.round(y_pred_prob)

y_pred_label=torch.round(torch.sigmoid(model_0(x_test.to(device)[:5])))

print(torch.eq(y_pred,y_pred_label))
y_pred.squeeze()

y_pred

torch.manual_seed(42)
epochs=100

x_train,y_train=x_train.to(device),y_train.to(device)
x_test,y_test=x_test.to(device),y_test.to(device)

for epochs in range(epochs):
  model_0.train()

  y_logits=model_0(x_train.to(device)).squeeze()
  y_pred=torch.round(torch.sigmoid(y_logits))

  loss=loss_fn(y_logits,
               y_train)
  acc=accuracy_fn(y_true=y_train,
                  y_pred=y_pred)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  model_0.eval()
  with torch.inference_mode():
    test_logits=model_0(x_test).squeeze()
    test_pred=torch.round(torch.sigmoid(test_logits))

    test_loss=loss_fn(test_logits,
                      y_test)
    test_acc=accuracy_fn(y_true=y_test,
                    y_pred=test_pred)

    if epochs%10==0:
      print(f"Epochs:{epochs}|loss:{loss:.5f},Acc:{acc:.2f}%|Test loss:{test_loss:.5f}, Test Acc:{test_acc:.2f}%")

"""#Make prediction"""

y_test[:5]

import requests
from pathlib import Path

if Path("helper_functions.py").is_file():
  print("helper_functions.py already exists , skipping download")
else:
  print("Downloading helper_file")
  request=requests.get("https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/refs/heads/main/helper_functions.py")
  with open("helper_functions.py", "wb") as f:
    f.write(request.content)
#Import the function after downloading the file
import helper_functions
from helper_functions import plot_predictions,plot_decision_boundary

plt.figure(figsize=(12,7))
plt.subplot(1,2,1)
plt.title("Train")
plot_decision_boundary(model_0,x_train,y_train)
plt.subplot(1,2,2)
plt.title("Test")
plot_decision_boundary(model_0,x_test,y_test)

"""#Improving a model"""

class circlemodelv1(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_1=nn.Linear(in_features=2,out_features=10)
    self.layer_2=nn.Linear(in_features=10,out_features=10)
    self.layer_3=nn.Linear(in_features=10,out_features=1)

  def forward(self,x):
    return self.layer_3(self.layer_2(self.layer_1(x)))

model_1=circlemodelv1().to(device)
model_1

model_1.state_dict()

loss_fn=nn.BCEWithLogitsLoss()
optimizer=torch.optim.SGD(params=model_1.parameters(),
                          lr=0.1)

torch.manual_seed(42)
torch.cuda.manual_seed(42)

epochs=1000

x_train,x_test=x_train.to(device),x_test.to(device)
y_train,y_test=y_train.to(device),y_test.to(device)

for epoch in range(epochs):
  model_1.train()

  y_logits=model_1(x_train).squeeze()
  y_prob=torch.round(torch.sigmoid(y_logits))

  loss=loss_fn(y_logits,
               y_train)
  acc=accuracy_fn(y_true=y_train,
                  y_pred=y_prob)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  model_1.eval()
  with torch.inference_mode():
    test_logits=model_1(x_test).squeeze()
    test_prob=torch.round(torch.sigmoid(test_logits))

    test_loss=loss_fn(test_logits,
                      y_test)
    test_acc=accuracy_fn(y_true=y_test,
                         y_pred=test_prob)

  if epoch % 100 == 0:
    print(f"Epochs:{epochs}|Loss:{loss:.3f}%|Acc:{acc:.2f}|Test loss:{test_loss:.3f}|Test acc:{test_acc:.2f}%")

#plot
plt.figure(figsize=(12,7))
plt.subplot(1,2,1)
plt.title("Train")
plot_decision_boundary(model_1,x_train,y_train)
plt.subplot(1,2,2)
plt.title("Test")
plot_decision_boundary(model_1,x_test,y_test)

"""#Prepare data to check our model really works"""

weight=0.7
bias=0.3

x_regression=torch.arange(0,1,0.01).unsqueeze(dim=1)
y_regression=weight*x_regression+bias

len(x_regression)
x_regression[:5],y_regression[:5]

train_split=int(0.8*len(x_regression))
x_train_regression,y_train_regression=x_regression[:train_split],y_regression[:train_split]
x_test_regression,y_test_regression=x_regression[train_split:],y_regression[train_split:]

len(x_train_regression),len(x_test_regression),len(y_train_regression),len(y_test_regression)

plot_predictions(train_data=x_train_regression.cpu(),
                 train_labels=y_train_regression.cpu(),
                 test_data=x_test_regression.cpu(),
                 test_labels=y_test_regression.cpu());

model_2=nn.Sequential(
    nn.Linear(in_features=1,out_features=10),
    nn.Linear(in_features=10,out_features=10),
    nn.Linear(in_features=10,out_features=1)
).to(device)

model_2

loss_fn=nn.L1Loss()
optimizer=torch.optim.SGD(params=model_2.parameters(),
                          lr=0.1)

torch.manual_seed(42)
torch.cuda.manual_seed(42)

epochs=1000

x_train_regression,y_train_regression=x_regression.to(device),y_regression.to(device)
x_test_regression,y_test_regression=x_regression.to(device),y_regression.to(device)

for epoch in range(epochs):
  model_1.train()

  y_log=model_2(x_train_regression)


  loss=loss_fn(y_log,
               y_train_regression)


  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  model_1.eval()
  with torch.inference_mode():
    test_log=model_2(x_test_regression)


    test_loss=loss_fn(test_log,
                      y_test_regression)


  if epoch % 100 == 0:
    print(f"Epochs:{epoch}|Loss:{loss:.3f}|Test loss:{test_loss:.3f}")

model_2.state_dict()

model_2.eval()
with torch.inference_mode():
  y_preds=model_2(x_test_regression)

plot_predictions(train_data=x_train_regression.cpu(),
                 train_labels=y_train_regression.cpu(),
                 test_data=x_test_regression.cpu(),
                 test_labels=y_test_regression.cpu(),
                 predictions=y_preds.cpu())

"""#The missing piece :non linerarity

#Recreating non_linearity
"""

import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import make_circles

n_samples=1000

x,y=make_circles(n_samples,
                 noise=0.03,
                 random_state=42)

plt.scatter(x[:,0],x[:,1], c=y , cmap=plt.cm.RdYlBu)

#convert data to tensor
import torch
from sklearn.model_selection import train_test_split

x=torch.from_numpy(x).type(torch.float)
y=torch.from_numpy(y).type(torch.float)

x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=42)
x_train[:5],y_test[:5]

"""#Building a model with non-linearity"""

from torch import nn
class circlemodelv2(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_1=nn.Linear(in_features=2,out_features=10)
    self.layer_2=nn.Linear(in_features=10,out_features=10)
    self.layer_3=nn.Linear(in_features=10,out_features=1)
    self.relu=nn.ReLU()

  def forward(self,x):
    return self.layer_3(self.relu(self.layer_2(self.relu(self.layer_1(x)))))

model_3=circlemodelv2().to(device)
model_3.to(device)

loss_fn=nn.BCEWithLogitsLoss()
optimizer=torch.optim.SGD(params=model_3.parameters(),
                          lr=0.1)

torch.manual_seed(42)
torch.cuda.manual_seed(42)
epochs=2000

x_train,y_train=x_train.to(device),y_train.to(device)
x_test,y_test=x_test.to(device),y_test.to(device)

for epoch in range(epochs):
  model_3.train()
  y_logits=model_3(x_train).squeeze()
  y_pr=torch.round(torch.sigmoid(y_logits))

  loss=loss_fn(y_logits,y_train)

  acc=accuracy_fn(y_true=y_train,
                  y_pred=y_pr)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  model_3.eval()
  with torch.inference_mode():
    test_logits=model_3(x_test).squeeze()
    test_pr=torch.round(torch.sigmoid(test_logits))
    test_loss=loss_fn(test_logits,y_test)
    test_acc=accuracy_fn(y_true=y_test,
                         y_pred=test_pr)

  if epoch % 100 ==0:
    print(f"Epochs:{epoch}| Loss:{loss:.5f}| Accuracy:{acc:.2f}%| Test Loss:{test_loss:.5f}| Test Accuracy:{test_acc:.2f}%")

model_3.eval()
with torch.inference_mode():
  y_preds=torch.round(torch.sigmoid(model_3(x_test.to(device)))).squeeze()
y_preds[:10],y_test[:10]

#plot decision boundaries
plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plt.title("Train")
plot_decision_boundary(model_3,x_train,y_train)
plt.subplot(1,2,2)
plt.title("Test")
plot_decision_boundary(model_3,x_test,y_test)

"""#REplicating non linear"""

A=torch.arange(-10,10,1,dtype=torch.float32)
A.dtype

plt.plot(A)

plt.plot(torch.relu(A))

def relu(x :torch.Tensor)->torch.Tensor:
  return torch.maximum(torch.tensor(0),x)

relu(A)

A

plt.plot(relu(A))

def sigmoid(x):
  return 1/(1+torch.exp(-x))

plt.plot(torch.sigmoid(A))

plt.plot(sigmoid(A))

"""#Putting it all together

#Creating toy multi class data
"""

import torch
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

x_blob,y_blob=make_blobs(n_samples=1000,
                        n_features=2,
                        centers=4,
                        cluster_std=1.5,
                        random_state=42)
x_blob=torch.from_numpy(x_blob).type(torch.float)
y_blob=torch.from_numpy(y_blob).type(torch.long)

x_blob_train,x_blob_test,y_blob_train,y_blob_test=train_test_split(x_blob,
                                                                   y_blob,
                                                                   test_size=0.2,
                                                                   random_state=42)
plt.figure(figsize=(10,7))
plt.scatter(x_blob[:,0],x_blob[:,1],c=y_blob,cmap=plt.cm.RdYlBu)

y_blob_train.shape

"""#Multi class classification model"""

device="cuda" if torch.cuda.is_available() else "cpu"
device

from torch import nn
#Build a multicalss classification
class blobmodel(nn.Module):
  def __init__(self,input_feature,output_feature,hidden_unit=8):
    super().__init__()
    self.liner_layer_stack=nn.Sequential(
        nn.Linear(in_features=input_feature,out_features=hidden_unit),
        # nn.ReLU(),
        nn.Linear(in_features=hidden_unit,out_features=hidden_unit),
        # nn.ReLU(),
        nn.Linear(in_features=hidden_unit,out_features=output_feature)
    )

  def forward(self,x):
    return self.liner_layer_stack(x)

model_4=blobmodel(input_feature=2,output_feature=4).to(device)
model_4

x_blob_train.shape,y_blob_train.shape

y_blob_train[:5]

torch.unique(y_blob_train)

loss_fn=nn.CrossEntropyLoss()
optimizer=torch.optim.SGD(params=model_4.parameters(),
                          lr=0.1)

model_4.eval()
with torch.inference_mode():
  y_logits=model_4(x_blob_test.to(device))
y_logits[:10]

y_pred_probs=torch.softmax(y_logits,dim=1)
print(y_logits[:5])
y_pred_probs[:5]

y_preds=torch.argmax(y_pred_probs,dim=1)
y_preds

y_blob_test

"""#Creating atraining loop"""

y_blob_test.dtype

x_blob_train.shape,y_blob_train.shape

torch.manual_seed(42)
torch.cuda.manual_seed(42)

epochs=1000

x_blob_train,y_blob_train=x_blob_train.to(device),y_blob_train.to(device)
x_blob_test,y_blob_test=x_blob_test.to(device),y_blob_test.to(device)

for epoch in range(epochs):
  model_4.train()
  y_logits=model_4(x_blob_train)
  y_pred=torch.softmax(y_logits,dim=1).argmax(dim=1)

  loss=loss_fn(y_logits,y_blob_train)

  acc=accuracy_fn(y_true=y_blob_train,y_pred=y_pred)

  optimizer.zero_grad()

  loss.backward()

  optimizer. step()

  model_4.eval()
  with torch.inference_mode():
    test_logits=model_4(x_blob_test)
    test_pred=torch.softmax(test_logits,dim=1).argmax(dim=1)

    test_loss=loss_fn(test_logits,y_blob_test)

    test_acc=accuracy_fn(y_true=y_blob_test,y_pred=test_pred)

  if epoch % 100 ==0:
    print(f"Epochs:{epoch} | Loss:{loss:.4f} | Accuracy:{acc:.2f}% | Test Loss:{test_loss:.4f} | Test Accuracy:{test_acc:.2f}%")

model_4.eval()
with torch.inference_mode():
  y_logits=model_4(x_blob_test)
y_logits[:10]

y_pred_probs=torch.softmax(y_logits,dim=1)
y_pred_probs[:10]

y_blob_test

y_pred_prob.argmax(dim=1)

x_blob_train.shape

plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plt.title("Train")
plot_decision_boundary(model_4,x_blob_train,y_blob_train)
plt.subplot(1,2,2)
plt.title("Test")
plot_decision_boundary(model_4,x_blob_test,y_blob_test)

"""###Few more classification model"""

!pip install torchmetrics

from torchmetrics import Accuracy

torchmetrics_accuracy=Accuracy(task="multiclass",num_classes=10).to(device)
torchmetrics_accuracy(y_preds,y_blob_test)

# ==============================
# Structured Pruning
# ==============================

import torch.nn.utils.prune as prune

# Prune 25% of neurons from the second Linear layer
prune.ln_structured(
    model_4.liner_layer_stack[1],
    name="weight",
    amount=0.25,
    n=2,
    dim=0
)

# Make pruning permanent
prune.remove(
    model_4.liner_layer_stack[1],
    "weight"
)

print("Structured pruning completed!")
